on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  WORK_DIR: /home/runner/work/simple-python-project/simple-python-project/flask

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 

    - name: debug
      run: |
        pwd
        ls -a
        echo WORK_DIR


    # - name: install dependencies
    #   run: |
    #     cd WORK_DIR
    #     pip install -r requirements.txt

    # - name: Lint with flake8
    #   run: |
    #     # fail if there are any flake8 errors
    #     cd WORK_DIR
    #     flake8 .