on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 

    - name: check dir
      run: pwd

    # - name: install dependencies
    #   run: |
    #     pip install -r requirements.txt

    # - name: Lint with flake8
    #   run: |
    #     # fail if there are any flake8 errors
    #     flake8 .