name: CD on aws ec2 instance
run-name: Run CD to dev - ${{ github.event_name }} on ${{ github.ref_name }}

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  run-linter:
    uses: ./.github/workflows/linter.yaml

  run-tests:
    uses: ./.github/workflows/test.yaml

  build:
    runs-on: ubuntu-latest
    needs: [run-linter, run-tests]
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: .ansible/main.yaml
        configuration: |
          [defaults]
          host_key_checking = false
        key: ${{secrets.AWS_SSH_PRIAVATE_KEY}}
        inventory: |
          [all]
          ${{secrets.AWS_IP_PATH}}
        options: |
          -e AWS_USER=${{secrets.AWS_USER}}
          -e GITHUB_REPO=${{github.repository}}
          -e APP_PATH=${{vars.APP_PATH}}