name: Tests for flask app
run-name: Run pytest - ${{ github.event_name }} on ${{ github.ref_name }}

on:
  workflow_run:
    workflows: ["Linter for flask app"]
    types:
      - completed
  

env:
  WORK_DIR: /home/runner/work/simple-python-project/simple-python-project/flask
        

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 

    - name: install dependencies
      run: |
        cd $WORK_DIR
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest